apps/cli/src/commands/boot-challenger.ts, packages/core/src/challenger/listenForAssertions.ts, packages/core/src/utils/resilientEventListener.ts
- Update the event listener to notify on error
- handle error in runtime and try to restart
- add notifications on restart and restart fail
=> Handle challenger errors and retry restart on error

apps/cli/src/commands/boot-challenger.ts, packages/core/src/challenger/isCheckingAssertions.ts, packages/core/src/challenger/listenForAssertions.ts, packages/core/src/operator/listenForChallenges.ts, packages/core/src/utils/getAssertion.ts, packages/core/src/utils/resilientEventListener.ts
Make challenger and operator use mainnet RPCs
=> Migrate to mainnet

apps/web-connect/src/features/wallet/routes/RedEnvelope2024.tsx, infrastructure/smart-contracts/contracts/upgrades/referee/Referee2.sol, infrastructure/smart-contracts/package.json, infrastructure/smart-contracts/scripts/upgradeReferee.mjs, infrastructure/smart-contracts/test/Fixture.mjs, infrastructure/smart-contracts/test/Referee.mjs
Update the Referee to let key holders stake esXai
=> Add staking to Referee

apps/web-connect/src/features/wallet/routes/RedEnvelope2024.tsx, packages/core/src/abis/RefereeAbi.ts, packages/core/src/operator/getBoostFactor.ts, packages/core/src/operator/index.ts, packages/core/src/operator/operatorRuntime.ts
Restructure the operatorRuntime for cleaner error management.
Handling errors inside callback functions.
=> Hanlde operator errors

apps/cli/package.json, apps/cli/src/commands/operator-control/operator-runtime.ts, apps/cli/src/utils/Logger.ts, apps/sentry-client-desktop/electron/main.ts, apps/sentry-client-desktop/src/components/blockpass/Blockpass.tsx, apps/sentry-client-desktop/src/features/home/SentryWallet.tsx, apps/sentry-client-desktop/src/features/home/dashboard/SentryNodeStatusCard.tsx, apps/sentry-client-desktop/src/features/home/modals/ExportSentryDrawer.tsx, apps/sentry-client-desktop/src/features/home/modals/actions-required/FundsInSentryWalletCard.tsx, apps/sentry-client-desktop/src/features/keys/HasKeys.tsx, apps/sentry-client-desktop/src/features/keys/StatusPulse.tsx, apps/sentry-client-desktop/src/features/storage/useStorage.tsx, apps/sentry-client-desktop/src/hooks/useOperatorRuntime.ts, apps/sentry-client-desktop/src/main.tsx, apps/web-connect/src/features/wallet/routes/RedEnvelope2024.tsx, pnpm-lock.yaml
In CLI for the operator (boot-operator) we us the new logger that will log to a daily file. This should be extended for the other cli commands.
In the electron app we now use the electron-log (log.info / log.error) for additional file logging.
=> Write logs to file

infrastructure/smart-contracts/contracts/staking-v2/BucketTracker.sol, infrastructure/smart-contracts/contracts/staking-v2/StakingPool.sol, infrastructure/smart-contracts/contracts/staking-v2/Utlis.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol
Adds Accesscontrol for Pool claim.
Adds Referee variable for maximum keys per pool.
Next steps:
- implement Referee V2 functions
- add events
=> Accesscontrol for pool claim

infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol, infrastructure/smart-contracts/contracts/staking-v2/StakingPool.sol, infrastructure/smart-contracts/contracts/staking-v2/TransparentUpgradable.sol, infrastructure/smart-contracts/contracts/staking-v2/Utlis.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol, infrastructure/smart-contracts/scripts/deployStakingV2.mjs
- add optimization for stack too deep
- implement read functions
TODO: Move deploy proxy contracts from Referee to reduce contract size
=> Fb staking v2

infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol
https://www.pivotaltracker.com/story/show/187193881
=> add require check for stakingEnabled when creating pool

infrastructure/smart-contracts/contracts/staking-v2/BucketTracker.sol, infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol, infrastructure/smart-contracts/contracts/staking-v2/StakingPool.sol, infrastructure/smart-contracts/scripts/deployStakingV2.mjs
- Add correct basepoint calculation
- Fix distribute rewards when no esXai stakers (#187206109)
- Fix bug refereeAddress on init stakingPool contract in factory
=> Fix getPoolUserData read

infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol
- implement bulk not revert on missing require
TODO:
- fix contract size
=> Fb bulk claim submit 

infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol
- Fix claim to pool if key assigned
- Add remove operator approval only if unstaked from last poolOwners Pool
- Add single mint for claimMultiple
=> Fb bulk claim replace rewards

infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol
- Bug fix: remove msg.sender from Referee Factory calls
- Add check for pool owner unstake alst key
- Add feature allow pool owner to unstake last key for 60 days wait
=> Review fixes

infrastructure/smart-contracts/test/Referee.mjs, infrastructure/smart-contracts/test/StakingV2.mjs
Relevant test is `Verify that keys in a pool with esXai staked with more challenges`. Lots of changes showing up because of some commenting/uncommenting
=> test for more wins for keys in pools with staked esXai

infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol, infrastructure/smart-contracts/contracts/staking-v2/StakingPool.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol, infrastructure/smart-contracts/test/stakingv2/UnStakingPeriods.mjs, infrastructure/smart-contracts/test/stakingv2/UpdatePool.mjs, infrastructure/smart-contracts/test/stakingv2/VerifyBoostFactor.mjs, packages/core/src/abis/PoolFactoryAbi.ts
Adds the updateRewardBreakdownDelayPeriod state variable for dynamic delay period of owner pool reward breakdown changes to take effect
Updated and ran the test suite
=> Add dynamic variable for reward breakdown update

packages/core/src/operator/operatorRuntime.ts
Made nodeLicense List unique for edge case of self operator approval
Readd check for KYC
=> add fix for self approval multiple key submission

apps/web-connect/src/features/header/Header.tsx
For https://www.pivotaltracker.com/story/show/187652370
Make the navbar home icon link to xai.games
=> Sentry.xai.games: Update Navbar home link

infrastructure/smart-contracts/contracts/xai-subsidy/Forwarder.sol, infrastructure/smart-contracts/contracts/xai-subsidy/subsidy-client-poc.js
For https://www.pivotaltracker.com/story/show/187699979
Implement the XAI Forwarder Upgradable contract.
Added a simple js poc to sign the metatransaction
=> add upgradable forwarder contract and client test poc

infrastructure/xai-relayer-api/src/api/routes/get_project_quotes.ts, infrastructure/xai-relayer-api/src/api/routes/get_user_quotes.ts, infrastructure/xai-relayer-api/src/api/routes/index.ts, infrastructure/xai-relayer-api/src/app.ts, infrastructure/xai-relayer-api/src/loaders/mongoose.ts, infrastructure/xai-relayer-api/src/models/Project.schema.ts, infrastructure/xai-relayer-api/src/models/UserProjectInfo.schema.ts, infrastructure/xai-relayer-api/src/models/types/IDBModel.ts, infrastructure/xai-relayer-api/src/models/types/IProject.ts, infrastructure/xai-relayer-api/src/models/types/Quota.ts, infrastructure/xai-relayer-api/src/models/types/UserProjectInfo.ts, infrastructure/xai-relayer-api/src/services/quota/getProjectQuota.ts, infrastructure/xai-relayer-api/src/services/quota/getUserQuota.ts
For https://www.pivotaltracker.com/n/projects/2671427/stories/187699973
- Adding the db schemas
- Adding new db model types
For https://www.pivotaltracker.com/n/projects/2671427/stories/187734399
Adding the quota implementation for project and user to project
- Adding endpoint route
- Adding service functions
- Adding Quota type
Now using cached connection only on first use of db not on server start from
https://github.com/xai-foundation/sentry/pull/168#discussion_r1624898195
=> Add db models and quota service implementaion

apps/cli/src/commands/export-challenge-info.ts, apps/web-staking/src/app/components/createPool/CreatePoolComponent.tsx, apps/web-staking/src/app/components/createPool/StakePoolKeyComponent.tsx, apps/web-staking/src/app/components/dashboard/constants/constants.ts, apps/web-staking/src/app/components/navbar/SidebarComponent.tsx, apps/web-staking/src/app/components/pool/PoolTierCard.tsx, apps/web-staking/src/app/components/redeem/History.tsx, apps/web-staking/src/app/components/stake/StakeComponent.tsx, apps/web-staking/src/app/components/stakeKeysComponent.tsx/StakingKeysDetailComponent.tsx, apps/web-staking/src/app/components/staking/AvailablePoolsTableComponent.tsx, apps/web-staking/src/app/components/staking/StakingOverviewComponent.tsx, apps/web-staking/src/app/components/staking/TableChunksComponents.tsx, apps/web-staking/src/app/components/staking/utils.ts, apps/web-staking/src/app/components/summary/SummaryComponent.tsx, apps/web-staking/src/app/components/ui/tooltips/TableTooltip.tsx, apps/web-staking/src/server/services/Pool.service.ts, apps/web-staking/src/services/web3.service.ts
Merging staking app fixes
Additionally fixing the static values for the Referee upgrade in https://www.pivotaltracker.com/story/show/187741373
=> Fb merge staking udpates

apps/cli/src/commands/export-challenge-info.ts
Bugfix for the challenge export
=> fix challenge export unclaimed count

apps/cli/src/commands/export-challenge-info.ts, apps/cli/src/commands/sync-staking-pools.ts, apps/cli/src/index.ts, infrastructure/smart-contracts/contracts/upgrades/referee/Referee8.sol, infrastructure/smart-contracts/scripts/upgradeReferee.mjs, infrastructure/smart-contracts/test/Fixture.mjs, packages/core/src/data-centralization/index.ts, packages/core/src/data-centralization/poolDataSync.ts, packages/core/src/subgraph/getPoolAddressesFromGraph.ts, packages/core/src/subgraph/index.ts, packages/sentry-subgraph-client/.graphclientrc.yml
For https://www.pivotaltracker.com/story/show/187741373
We add the new Referee with the updated values in the initializer
For https://www.pivotaltracker.com/story/show/187748582
We add the syncing script to the cli for syncing all pools in the database
=> Fb update referee config

infrastructure/smart-contracts/contracts/xai-subsidy/Forwarder.sol, infrastructure/smart-contracts/contracts/xai-subsidy/Test/ForwarderTestNFT.sol, infrastructure/smart-contracts/contracts/xai-subsidy/Test/ForwarderTestReceiver.sol, infrastructure/smart-contracts/contracts/xai-subsidy/Test/ForwarderTestToken.sol, infrastructure/smart-contracts/hardhat.config.cjs, infrastructure/smart-contracts/scripts/xai-deploy/deployForwarder.mjs, infrastructure/smart-contracts/test/Fixture.mjs, infrastructure/smart-contracts/test/deployInfrastructureArbOne.mjs, infrastructure/smart-contracts/test/deployInfrastructureXai.mjs, infrastructure/smart-contracts/test/gasSubsidy/Forwarder.mjs
For https://www.pivotaltracker.com/story/show/187699986
- Adding the Forwarder testcase
- Restructuring the test fixture for multiple deployment setups like for the arb1 set and the xai set
- Adding test contracts for PM testing
- Adding the deployment script for the forwarder
=> Fb gas subsidy testcases

apps/web-staking/src/app/components/dashboard/TableComponent.tsx, apps/web-staking/src/app/components/pool/PoolOverViewCard.tsx, apps/web-staking/src/app/components/staking/AvailablePoolsTableComponent.tsx, apps/web-staking/src/app/components/staking/StakedPoolsTable.tsx, apps/web-staking/src/app/components/staking/TableChunksComponents.tsx, apps/web-staking/src/app/components/staking/utils.ts, apps/web-staking/src/app/components/summary/SummaryComponent.tsx, apps/web-staking/src/app/hooks/useGetTiers.ts
For https://www.pivotaltracker.com/n/projects/2671427/stories/187756381
=> Merge pool tier label loading delay

apps/cli/src/commands/start-centralization-runtime.ts, infrastructure/sentry-subgraph/generated/schema.ts, infrastructure/sentry-subgraph/schema.graphql, infrastructure/sentry-subgraph/schema/events/PoolFactory.graphql, infrastructure/sentry-subgraph/sepolia.subgraph.yaml, infrastructure/sentry-subgraph/src/referee.ts, infrastructure/sentry-subgraph/src/utils/updatePoolChallengeOnClaim.ts, packages/core/src/data-centralization/dataCentralizationRuntime.ts, packages/core/src/data-centralization/types.ts, packages/core/src/subgraph/getPoolRewardRate.ts, packages/core/src/subgraph/getRewardRatesFromGraph.ts, packages/core/src/subgraph/index.ts, packages/core/src/utils/index.ts, packages/core/src/utils/sendSlackNotification.ts, packages/sentry-subgraph-client/.graphclientrc.yml
https://www.pivotaltracker.com/story/show/187088418
=> Fb slack messages fix

infrastructure/sentry-subgraph/generated/schema.ts, infrastructure/sentry-subgraph/schema.graphql, infrastructure/sentry-subgraph/schema/events/PoolFactory.graphql, infrastructure/sentry-subgraph/sepolia.subgraph.yaml, infrastructure/sentry-subgraph/src/referee.ts, infrastructure/sentry-subgraph/src/utils/updatePoolChallengeOnClaim.ts
For:
- https://www.pivotaltracker.com/story/show/187666668
- https://www.pivotaltracker.com/story/show/187666744
- https://www.pivotaltracker.com/story/show/187666788
This adds the PoolChallenge entity and the syncing for it in the referee sync
=> Add pool to challenge entity, udpate syncing in referee

packages/core/src/data-centralization/dataCentralizationRuntime.ts, packages/core/src/data-centralization/types.ts, packages/core/src/subgraph/getPoolRewardRate.ts, packages/core/src/subgraph/getRewardRatesFromGraph.ts, packages/core/src/subgraph/index.ts
For https://www.pivotaltracker.com/story/show/187613246
This add the listener for challenges to the data sync runtime
=> add reward sync for pools on challenge event

packages/core/src/data-centralization/dataCentralizationRuntime.ts, packages/core/src/data-centralization/types.ts, packages/core/src/subgraph/getRewardRatesFromGraph.ts, packages/sentry-subgraph-client/.graphclientrc.yml
Added field to database for total esXai claimed for reward rate reconciliation.
=> Added total esXai Claimed to Pool Infos

apps/web-staking/src/app/components/pool/PoolStakingInfo.tsx, apps/web-staking/src/app/components/pool/PoolStakingInfoChild.tsx, apps/web-staking/src/app/components/summary/StakingCards.tsx, apps/web-staking/src/app/components/summary/SummaryComponent.tsx
Copy from https://github.com/CryptITAustria/sentry/pull/51
Needs to be merged into prod repo.
fixed mobile view for reward rate pool details page
task: https://www.pivotaltracker.com/story/show/187831401
=> Fix reward rates pool details

apps/web-staking/src/app/components/staking/AvailablePoolsTableComponent.tsx, apps/web-staking/src/app/components/staking/StakedPoolsTable.tsx, apps/web-staking/src/app/components/staking/TableChunksComponents.tsx
Copy from https://github.com/CryptITAustria/sentry/pull/52
fixed table alignments for mobile
added compact notation
updated column header copy for key rate
task: https://www.pivotaltracker.com/story/show/187822481
=> Fix table alignments

apps/web-staking/src/app/hooks/useGetMaxKeyPerPool.ts
Copy from https://github.com/CryptITAustria/sentry/pull/54
fixed staking UI shows incorrect max keys
task: https://www.pivotaltracker.com/story/show/187833427
=> fix: fixed max keys showing

infrastructure/smart-contracts/contracts/upgrades/esXai/esXai3.sol, infrastructure/smart-contracts/scripts/upgradeEsXai.mjs, infrastructure/smart-contracts/test/Fixture.mjs
https://www.pivotaltracker.com/story/show/187790906
=> Added KYC Check at Redemption Completion Based on # of Keys owned

infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol, infrastructure/smart-contracts/scripts/upgradeNodeLicense.mjs
Sell Keys in Xai
Remove Refund Function
Update Promo Code Logic
https://www.pivotaltracker.com/story/show/187790711
https://www.pivotaltracker.com/story/show/186638876
https://www.pivotaltracker.com/story/show/187784225
=> Sell Keys in Xai/esXai

Dockerfile, apps/web-staking/package.json, apps/web-staking/src/context/index.tsx, package.json, pnpm-workspace.yaml
Merge integration of web-staking into monorepo
=> Fb staking build

apps/web-connect/src/features/checkout/Checkout.tsx, packages/ui/src/rebrand/buttons/TextButton.tsx, packages/ui/src/rebrand/icons/IconsComponents.tsx, packages/ui/src/rebrand/index.ts, packages/ui/src/rebrand/tooltip/Tooltip.tsx, packages/ui/src/rebrand/tooltip/index.ts
For https://www.pivotaltracker.com/n/projects/2671427/stories/187716095
This now uses the new custom tooltip from the rebrand on sentry.xai.games.
Dev deploy is currently here
https://cryptitaustria.github.io/sentry/
=> Fix sentry tooltip

packages/ui/src/rebrand/steppers/MainStepper.tsx
task: https://www.pivotaltracker.com/story/show/187893297
- fixed cut off input number on sentry page
=> Fix cut off input number

apps/sentry-client-desktop/src/features/home/dashboard/SentryNodeStatusCard.tsx, apps/sentry-client-desktop/src/features/sidebar/SidebarRoot.tsx
- fixed verification added wallets
- fixed start node button on click function
task: https://www.pivotaltracker.com/story/show/187891854
=> Fix verification added wallets

infrastructure/smart-contracts/contracts/tiny-keys/RefereeGetWinningKeyCount.sol
Task: https://www.pivotaltracker.com/n/projects/2671427/stories/187869953 
create function getWinningKeyCount. takes input stakedKeyCount and boostfactor. adds a random amount to the winningKeyCount and returns it. 
BLOCKER: Added to separate file as new Contract Referee9 not merged yet. needs to be incorporated.
=> function getWinningKeyCount and function to simulate randomness.

infrastructure/smart-contracts/contracts/RefereeEvents.sol, infrastructure/smart-contracts/contracts/tiny-keys/RefereeGetWinningKeyCount.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee9A.sol
https://www.pivotaltracker.com/story/show/187900712
https://www.pivotaltracker.com/story/show/187900724
Removed event definitions from referee.
Created RefereeEvents library for event definitions.
Also, had to comment out an incorrect param in getWinningKeyCount function to get the contracts to compile.
=> Moved Referee Event Definitions to Library

infrastructure/smart-contracts/contracts/RefereeCalculations.sol, infrastructure/smart-contracts/contracts/tiny-keys/RefereeGetWinningKeyCount.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee9A.sol
https://www.pivotaltracker.com/story/show/187900841
https://www.pivotaltracker.com/story/show/187900846
1. Created RefereeCalculations library
2. Moved calculation functions from Referee to the new external library
3. Also, had to comment out an incorrect param in getWinningKeyCount function to get the contracts to compile.
=> Moved Referee calculations to external library

infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol, infrastructure/smart-contracts/test/stakingv2/CreatePool.mjs
https://www.pivotaltracker.com/n/projects/2671427/stories/187742811
Add kyc check to poolFactory
Add error code for kyc check in poolFactory
Add test case to check not kyc approved owner cannot create a pool
TODO: We need to add the new error code to the frontend for poolCreate
=> Fb tiny keys poolfactory kyc check

apps/web-connect/src/features/checkout/components/ActionSection.tsx, apps/web-connect/src/features/checkout/components/ChooseCurrencyRow.tsx
https://www.pivotaltracker.com/story/show/187934517
Fixed approval button to properly connect the the "Approve Function"
=> Fixed UI Mint with Xai Approval Button

apps/web-staking/src/app/components/icons/SortArrowDown.tsx, apps/web-staking/src/app/components/icons/SortArrowUp.tsx, apps/web-staking/src/app/components/staking/AvailablePoolsTableComponent.tsx, apps/web-staking/src/app/components/staking/StakingOverviewComponent.tsx, apps/web-staking/src/app/components/staking/TableChunksComponents.tsx, apps/web-staking/src/app/staking/page.tsx, apps/web-staking/src/server/services/Pool.service.ts, packages/ui/src/rebrand/icons/SortArrowDown.tsx, packages/ui/src/rebrand/icons/SortArrowUp.tsx
- Added ascending/descending sort for available pools table. 
- Added icons to show what sort is now.
- Added hover effect to table titles and paddings for lg+ devices.
[Ticket](https://www.pivotaltracker.com/n/projects/2671427/stories/187907855)
=> UI: Update pool sort feature on staking app

apps/web-connect/tailwind.config.js, packages/ui/src/rebrand/dropdown/Dropdown.tsx
- added colors to tailwind config
- added clip-path to dropdown to make it independent from .css files
[Ticket](https://www.pivotaltracker.com/n/projects/2671427/stories/187941587)
=> Fix dropdown styling

infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
Update the new AssertionSubmitted event to emit `eligibleForPayout`
=> Update Referee event for subgraph

infrastructure/sentry-subgraph/abis/Referee.json, infrastructure/sentry-subgraph/generated/Referee/Referee.ts, infrastructure/sentry-subgraph/generated/schema.ts, infrastructure/sentry-subgraph/schema.graphql, infrastructure/sentry-subgraph/schema/events/PoolFactory.graphql, infrastructure/sentry-subgraph/schema/events/Referee.graphql, infrastructure/sentry-subgraph/sepolia.subgraph.yaml, infrastructure/sentry-subgraph/src/referee.ts, infrastructure/sentry-subgraph/subgraph.yaml
For https://www.pivotaltracker.com/story/show/187869828
- add challange sync in pool submission handler
- add pool challange sync (this seems very redundant with pool submissions)
For https://www.pivotaltracker.com/story/show/187906537
- adding new event handlers for updated events
- add exit condition in outdated events
Sepolia version deployed at
https://subgraphs.alchemy.com/subgraphs/6221/versions/22860
TODO:
The aidrop contracts auto stake is currently not being registered and loggin an error in the pool facotry sync script
=> Fb tiny keys subgraph update submissions

apps/web-connect/src/features/checkout/Checkout.tsx, apps/web-connect/src/features/checkout/components/ActionSection.tsx, apps/web-connect/src/features/checkout/components/ChooseQuantityRow.tsx, apps/web-connect/src/features/checkout/components/PurchaseSuccessful.tsx, apps/web-connect/src/features/hooks/contract/useContractWrites.ts, apps/web-connect/src/features/hooks/web-buy-keys/useWebBuyKeysOrderTotal.ts
https://www.pivotaltracker.com/story/show/187934517
This is a fix for the approval button not refreshing properly upon contract state changes.
There is still one additional fix needed, I still need to fix the redirect upon mint completion. That will be coming in a separate PR.
=> Fix Approval Button Functionality

apps/web-staking/src/server/services/Pool.service.ts
https://www.pivotaltracker.com/story/show/187869816
Update return values to return pending instead of current values.
=> Fix web staking app to return a pools' pending share values

infrastructure/smart-contracts/contracts/drops/TinyKeysAirdrop.sol, infrastructure/smart-contracts/test/NodeLicenseTinyKeys.mjs, infrastructure/smart-contracts/test/tinykeys/RefereePoolSubmissions.mjs
https://www.pivotaltracker.com/story/show/187965482
Fix off by one error on max supply update.
Fix/update tests.
=> Fix airdrop bug and tests

apps/web-connect/src/features/checkout/components/PromoCodeRow.tsx, apps/web-connect/src/features/hooks/promo/usePromoCodeHandler.ts, apps/web-connect/src/features/hooks/web-buy-keys/useWebBuyKeysOrderTotal.ts, packages/core/src/node-license/getPromoCode.ts
Fixed Promo Code as Address =>https://www.pivotaltracker.com/story/show/187975428
Originally for this => https://www.pivotaltracker.com/story/show/187784225
Updated core function to now check for address as promo code.
Renamed "handleSubmit" to "applyPromoCode" for naming clarity.
=> Fix PromoCode as Address Bug

infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol, infrastructure/smart-contracts/test/StakingV2.mjs, infrastructure/smart-contracts/test/stakingv2/StakeAndUnstakeMultiplePools.mjs
https://www.pivotaltracker.com/story/show/187963687
Fix staking bug in pool factory and write tests to confirm it is fixed.
I confirmed the new tests failed before the fix was implemented and are now passing.
=> Bug fix pool factory remove user from pool

infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
https://www.pivotaltracker.com/story/show/187976342
Update claim referral reward function to include re-entrancy protection.
=> Fix Claim Referral Reward Re-entrancy 

apps/web-staking/src/app/components/staking/StakingOverviewComponent.tsx
- added modal when there is "modal" search param
- added logic to close modal
Changes are requested for https://github.com/xai-foundation/sentry/pull/282
=> Mint success redirect to staking app | Web-Staking changes

apps/web-connect/src/features/checkout/Checkout.tsx, apps/web-connect/src/features/checkout/components/ChooseQuantityRow.tsx
https://www.pivotaltracker.com/story/show/187971340
Redirect to staking app on successful mint.
Url needs to be updated for production, currently set for develop.
=> Redirect Refactor

infrastructure/smart-contracts/scripts/stats/saveStakingStats.mjs, packages/core/src/subgraph/getAllSentryWallets.ts, packages/core/src/subgraph/index.ts
https://www.pivotaltracker.com/story/show/188000144
Script to generate a CSV report with staking data from the subgraph.
=> Staking Stats Script

packages/core/src/config.ts
[Fix Config File](https://www.pivotaltracker.com/story/show/188019963)
Fix process not defined bug in config file
=> Fix Config File ENV Bug

apps/web-staking/src/app/components/staking/SearchBarComponent.tsx, apps/web-staking/src/app/components/staking/StakingOverviewComponent.tsx, apps/web-staking/src/app/components/ui/inputs/BaseInput.tsx, apps/web-staking/src/app/staking/page.tsx, apps/web-staking/src/server/services/Pool.service.ts
https://www.pivotaltracker.com/story/show/187943002
Added esXai filter for staking pools page
=> Added ability to filter by esXai stake amount

README.md
- Added additional info about web ui components
[Ticket](https://www.pivotaltracker.com/n/projects/2671427/stories/187920991)
=> Document Global UI Components

apps/web-connect/src/features/hooks/contract/useContractWrites.ts
https://www.pivotaltracker.com/story/show/187971340
Removed lines triggering desktop app prompt
=> Fix Desktop Opening on Mint Success

apps/web-connect/src/features/hooks/contract/useContractWrites.ts
[Fix Mint with Aeth](https://www.pivotaltracker.com/story/show/188028563)
Fixed discount being applied twice.
=> Fix Mint With Eth Bug

apps/web-connect/src/features/checkout/Checkout.tsx
[Fix Page Jump on Qty Change](https://www.pivotaltracker.com/story/show/188006759)
Added min height to prevent "page jump" on qty change.
=> UI Fix Page Jump On Qty Change

infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
[Bug Ticket](https://www.pivotaltracker.com/story/show/188006801)
Fix Incorrect Operation That Was Reversed
=> Fix Incorrect Operation That Was Reversed

apps/web-connect/src/features/checkout/components/PurchaseSuccessful.tsx
[Fix Modal Opening](https://www.pivotaltracker.com/story/show/188028388)
Stop opening modal on return to client.
=> Fix Modal Opening on Return to Client

infrastructure/smart-contracts/.openzeppelin/arbitrum-one.json, infrastructure/smart-contracts/hardhat.config.cjs, infrastructure/smart-contracts/scripts/upgradeReferee.mjs
Merge previous production deploys
=> push lates prod deploys

infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
[Ticket](https://www.pivotaltracker.com/story/show/188036668)
add claim for owner bulkSubmission
Did not remove claimRewards/claimMultiple as users will still need to call those for up to 6 months to claim for previous existing submissions.
=> Add Claim Bulk Rewards

infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
[Update Stake Functions](https://www.pivotaltracker.com/story/show/188036661)
=> Update Stake Functions To Check for Owner Bulk Submission

infrastructure/nitro-node-wrapper/publisher/README.md, infrastructure/nitro-node-wrapper/publisher/manual-sync/RollupAdminLogicAbi.js, infrastructure/nitro-node-wrapper/publisher/manual-sync/loadNodeCreatedEvents.mjs, infrastructure/nitro-node-wrapper/publisher/manual-sync/manual-sync-cdn.mjs, infrastructure/nitro-node-wrapper/publisher/package.json, infrastructure/nitro-node-wrapper/sample.env
For https://www.pivotaltracker.com/story/show/188043977
Add a manual sync for the Public Node CDN
- update packages
- add dotenv for local testing
- add rollup abi for NodeCreated decoding
- add helper functon for fetching events
- update readme
=> Add manual sync script for NodeCreated CND updates

apps/web-connect/src/features/checkout/components/ActionSection.tsx, apps/web-connect/src/features/hooks/web-buy-keys/useWebBuyKeysOrderTotal.ts
[Ticket](https://www.pivotaltracker.com/story/show/188059536)
Fix Mint with Eth button state when wallet has insufficient funds.
=> Fix Mint with Eth Bug when wallet has insufficient funds

infrastructure/smart-contracts/contracts/RefereeCalculations.sol, infrastructure/smart-contracts/contracts/drops/TinyKeysAirdrop.sol, infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol, infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol
[Ticket](https://www.pivotaltracker.com/story/show/188049686)
Smart contract audit fixes
=> Smart Contract Audit Fixes

infrastructure/sentry-subgraph/generated/schema.ts, infrastructure/sentry-subgraph/schema.graphql, infrastructure/sentry-subgraph/schema/events/Referee.graphql, infrastructure/sentry-subgraph/src/referee.ts, infrastructure/sentry-subgraph/subgraph.yaml
For [Ticket](https://www.pivotaltracker.com/story/show/188036679)
Updated SentryWallet and Challenge graphql entity with bulkSubmission relationships.
Updated handleBulkSubmission handler to create sentry wallet submission for unstaked keys.
Subgraph deployed to sepolia, see link in ticket.
=> Updated bulk submission entity for linking to sentrywallet

infrastructure/smart-contracts/scripts/deployTinyKeys.mjs, infrastructure/smart-contracts/scripts/deployTinyKeysSepolia.mjs, infrastructure/smart-contracts/scripts/tiny-keys/processAirdrop.mjs, infrastructure/smart-contracts/scripts/tiny-keys/tinyKeysAirdropDeployer.mjs
[Update Tiny Keys Deployment Scripts](https://www.pivotaltracker.com/story/show/188092301)
=> Update Tiny Keys Deployment Scripts

packages/core/src/operator/checkRefereeBulkSubmissionCompatible.ts, packages/core/src/operator/index.ts, packages/core/src/operator/operator-runtime/listenForChallengesCallback.ts, packages/core/src/subgraph/getCurrentRefereeVersionFromGraph.ts, packages/core/src/subgraph/index.ts
[Ticket](https://www.pivotaltracker.com/story/show/188044068)
Updated operator to check referee version
=> Updated operator to check referee version

packages/core/src/config.ts, packages/core/src/node-license/getPriceForQuantity.ts, packages/core/src/utils/getEsXaiAllowance.ts, packages/core/src/utils/getEsXaiBalance.ts, packages/core/src/utils/getEthXaiExchangeRate.ts, packages/core/src/utils/getProvider.ts, packages/core/src/utils/getXaiAllowance.ts, packages/core/src/utils/getXaiBalance.ts
[Ticket](https://www.pivotaltracker.com/story/show/188055898)
=> Update Alchemy RPC Endpoint

infrastructure/smart-contracts/contracts/RefereeCalculations.sol, infrastructure/smart-contracts/test/utils/getWinningKeyCountLocal.mjs
Still need to create story and add ticket. 
Remove irrelevant calculation in contract function and local test function.
=> Update Get Winning Key Count Function/Test

apps/web-staking/src/services/web3.service.ts
[Ticket](https://www.pivotaltracker.com/story/show/188095281)
=> Fix UnStake Bug

infrastructure/sentry-subgraph/abis/TinyKeysAirdrop.json, infrastructure/sentry-subgraph/generated/PoolFactory/TinyKeysAirdrop.ts, infrastructure/sentry-subgraph/generated/TinyKeysAirdrop/TinyKeysAirdrop.ts, infrastructure/sentry-subgraph/sepolia.subgraph.yaml, infrastructure/sentry-subgraph/src/pool-factory.ts, infrastructure/sentry-subgraph/src/tiny-keys-airdrop.ts, infrastructure/sentry-subgraph/subgraph.yaml, infrastructure/smart-contracts/contracts/drops/TinyKeysAirdrop.sol
[Ticket](https://www.pivotaltracker.com/story/show/188074236)
Subgraph is deployed and synced on Sepolia for testing, link is in the ticket.
=> Add Subgraph Logic for Auto Stake on Airdrop

apps/web-connect/src/features/checkout/Checkout.tsx, apps/web-connect/src/features/checkout/components/PurchaseSuccessful.tsx, apps/web-connect/src/main.tsx, apps/web-connect/tailwind.config.js, packages/ui/src/features/tooltip/Tooltip.tsx, packages/ui/src/rebrand/icons/BackArrow.tsx, packages/ui/src/rebrand/icons/IconsComponents.tsx
For https://www.pivotaltracker.com/story/show/188007460
Update the key sale success page.
Add shared links as export in Checkout, update url for wagmi metadata.
=> Fb keysale success

apps/web-connect/src/features/checkout/components/ChooseQuantityRow.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188121268)
=> Fix Qty Clickable

apps/sentry-client-desktop/package.json, package.json, pnpm-lock.yaml
For https://www.pivotaltracker.com/story/show/187830557
Update the monorepos npm packages.
=> Update npm packages from audit

apps/cli/src/commands/operator-control/process-unclaimed-challenges.ts, apps/cli/src/index.ts, packages/core/src/operator/index.ts, packages/core/src/operator/processUnclaimedChallenges.ts, packages/core/src/subgraph/getSentryKeysForUnclaimedFromGraph.ts, packages/core/src/subgraph/index.ts
For https://www.pivotaltracker.com/story/show/188074371
Adding a processor runtime that will process unclaimed challenges filtered by a max key id.
Added cli command to start the runtime.
=> add process unclaimed key based challenges, add cli command to start

apps/web-connect/src/features/checkout/components/AgreementCheckboxes.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188101446)
Updated the language for KYC in the Sentry app.
=> Updated Sentry Checkbox Message

packages/core/src/operator/checkRefereeBulkSubmissionCompatible.ts, packages/core/src/operator/operator-runtime/bootOperatorRuntime.ts, packages/core/src/operator/operator-runtime/listenForChallengesCallback.ts, packages/core/src/operator/operator-runtime/operator-v1/loadOperatorKeysFromGraph.ts, packages/core/src/operator/operatorRuntime.ts
[Ticket](https://www.pivotaltracker.com/story/show/188100564)
=> Operator check referee version

apps/web-staking/src/app/components/createPool/CreatePoolComponent.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188065799)
Updated redirect page to pool summary when successfully creating a new pool.
=> Create Pool Redirect

apps/cli/src/commands/monitor-node-created.ts, apps/cli/src/index.ts, packages/core/src/event-monitor/nodeCreatedMonitor.ts, packages/core/src/index.ts, packages/core/src/utils/sendSlackNotification.ts
For https://www.pivotaltracker.com/story/show/187956740
Add cli command for NodeCreated event monitor.
Format slack notification wrapper, add displable unfold for embedded links
=> Add NodeCreated event monitor

infrastructure/smart-contracts/contracts/RefereeCalculations.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
[Ticket 1](https://www.pivotaltracker.com/story/show/187974033)
[Ticket 2](https://www.pivotaltracker.com/story/show/187974013)
=> Update Time Based Emissions

apps/web-connect/src/features/checkout/components/ChooseQuantityRow.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188121268)
=> Fix max Qty

apps/web-connect/src/features/checkout/Checkout.tsx, apps/web-connect/src/features/checkout/components/PromoCodeRow.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188116039)
Updated PromoCodeRow.tsx to pull promo code from query params (if exists) and auto-applies the promo code.
NOTE: this change requires [this ticket](https://www.pivotaltracker.com/story/show/188116043) to be merged first.
=> pull promo code from query params and apply

packages/core/src/operator/operator-runtime/operator-v1/bootOperatorRuntime.ts
[Ticket](https://www.pivotaltracker.com/story/show/188165725)
Fixed build error. It was caused by a core function having it's params updated and one of the implementations did not get updated. I will own that one!
Testing: confirmed the cli builds successfully after the fix.
=> Fixed build error

apps/web-connect/src/features/hooks/promo/usePromoCodeHandler.ts
=> Fix Re-render

infrastructure/smart-contracts/contracts/RefereeCalculations.sol, infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
For https://www.pivotaltracker.com/story/show/188283392
Added the aduit review fixes
Minor updates, would not show up in manual test, this will have to be covered within the testsuite. 
AQny test ticket should view the audit comments and make sure these cases are covered.
=> Audit review fixes

infrastructure/smart-contracts/package.json, infrastructure/smart-contracts/scripts/mock-assertion-test/mock-assertion-test.mjs, packages/core/src/utils/getNodeConfirmedEvents.ts, packages/core/src/utils/index.ts
[Ticket](https://www.pivotaltracker.com/story/show/187985818)
Created a script to allow testing of the operator with confirm data from Mainnet.
Script does the following:
1. Gets real assertion data from mainnet
2. Creates and confirms a node on the Sepolia mock rollup.
3. Waits 15 seconds and repeats the above for the next assertion.
4. Wait 2 minutes  and repeats steps 1 & 2 for the next assertion triggering a batch challenge.
5. Wait 2 minutes and 10 seconds and  repeats steps 1 & 2 for the next assertion triggering a single challenge.
Tested by starting the challenger and operator and then running the script. After that I confirmed the expected txs on chain and logs in the run times.
=> Operator test batched challenge

apps/web-connect/src/features/checkout/components/ActionSection.tsx, apps/web-connect/src/features/hooks/web-buy-keys/useWebBuyKeysOrderTotal.ts, packages/ui/src/rebrand/buttons/PrimaryButton.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188333570)
Updated styling for mint with credit card button. 
Adjusted the U/I component to accept an outline variation to match the new styles.
Updated the text/copy. 
Made button conditionally render only if wallet is connected.
This should be merged into [PR#437](https://github.com/xai-foundation/sentry/pull/437) before it is merged.
Testing, has been tested locally by starting and observing the styles and conditional rendering.
=> Updated styling for mint with credit card button

infrastructure/smart-contracts/test/NodeLicenseTinyKeys.mjs, infrastructure/smart-contracts/test/Referee.mjs, infrastructure/smart-contracts/test/get-winning-key-count/WinningKeyCountSimulations.mjs, infrastructure/smart-contracts/test/stakingv2/StakeKeysToPool.mjs, infrastructure/smart-contracts/test/stakingv2/SubmittingAndClaiming.mjs, infrastructure/smart-contracts/test/tinykeys/RefereeBulkSubmissions.mjs
[Ticket](https://www.pivotaltracker.com/story/show/188311226)
* Updated all smart contract unit tests to work with tiny keys changes
Tested by running `pnpm test` and verifying all tests pass.
NOTE: some tests will intentionally fail because they require functions to exist on the smart contract but we leave them commented out to reduce contract sizes. To make these tests pass, follow the instructions at the top of the test to resolve.
=> Fix Remaining Contract Tests

apps/web-connect/src/features/checkout/Checkout.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188355208)
Hide logo column on mobile screens to fix alignment issues. 
Testing: deployed on develop and tested with metamask mobile to confirm mobile view meets ticket requirements.
=> UI mobile styling improvements

infrastructure/smart-contracts/contracts/upgrades/esXai/esXai2.sol, infrastructure/smart-contracts/scripts/upgradeEsXai.mjs
[Ticket](https://www.pivotaltracker.com/story/show/188462806)
Updated esXai2 contract to include two optimized reader functions for redemptions. 
Testing, tested by deploying on Sepolia and confirming the read functions work through the explorer.
=> Updated esXai contract to include bulk read functions for redemptions

apps/web-connect/src/main.tsx, apps/web-staking/src/app/components/dashboard/DashboardStakingInfo.tsx, apps/web-staking/src/app/components/redeem/History.tsx, apps/web-staking/src/app/components/redeem/RedeemComponent.tsx, apps/web-staking/src/app/hooks/useGetRedemptions.ts, apps/web-staking/src/app/hooks/useSessionStorage.ts, apps/web-staking/src/assets/abi/esXaiAbi.ts, apps/web-staking/src/services/redemptions.service.ts, apps/web-staking/src/services/web3.service.ts
[Ticket](https://www.pivotaltracker.com/story/show/188463059)
Moved previously developed redemptions improvement loading feature from redemption-vouchers branch.
Updated useGetRedemptions hook to use the new reader functions in esXai2.
Testing: tested locally by loading a wallet with hundreds of redemptions. Pending additional testing on the PR link upon build.
=> Improve UI Redemptions Loading

packages/core/src/config.ts
[Ticket](https://www.pivotaltracker.com/story/show/188164982)
Added refereeCalculations address to config file. 
Still need to add airdrop address after airdrop contract has been deployed.
=> feat: Added referee calculations address to config file.

apps/web-connect/src/app/App.tsx, apps/web-connect/src/features/checkout/Checkout.tsx, apps/web-connect/src/features/checkout/components/ActionSection.tsx
For https://www.pivotaltracker.com/story/show/188538617
Remove crossmint & mint with xai.
Tested in live call on release.
=> Remove crossmint and mint with token for release

infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
For 
[#188548404](https://www.pivotaltracker.com/story/show/188548404)
[#188548393](https://www.pivotaltracker.com/story/show/188548393)
Add the `adminMintTo` and `adminTransferBatch` to NodeLicense8.
Add the new state for admin transfer id.
Added the new roles.
=> Magic eaden sale interface

infrastructure/smart-contracts/contracts/sample/SampleERC20.sol, infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol, infrastructure/smart-contracts/scripts/tiny-keys/deployTinyKeys.mjs, infrastructure/smart-contracts/test/Fixture.mjs, infrastructure/smart-contracts/test/NodeLicense.mjs
[Mint With USDC Ticket](https://www.pivotaltracker.com/story/show/188538162)
[Claim Rewards Ticket](https://www.pivotaltracker.com/story/show/188569230)
* Added `mintToWithUSDC()` functio to `NodeLicense8` contract.
* Added test for minting with sample USDC token.
* Added test for minting with sample USDC token using a promo code.
* Added test for claiming referral rewards in USDC.
Tested by running `pnpm test` and observing successful test results:
```
✔ Check if can mint with USDC to recipient address
✔ Check if can mint with USDC to recipient address using a valid promo code (38ms)
✔ Check if can claim USDC referral rewards (40ms)
```
=> Node License USDC Minting

infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol
[Ticket](https://www.pivotaltracker.com/story/show/188548369)
Added New events for PoolFactory2 for more robust tracking in the subgraph.
Testing, deployed on [Sepolia](https://sepolia.arbiscan.io/address/0x87Ae2373007C01FBCED0dCCe4a23CA3f17D1fA9A).
Additional functionality in this [ticket](https://www.pivotaltracker.com/story/show/188575400).
=> Add New Events to PoolFactory2

apps/web-connect/src/features/checkout/Checkout.tsx, apps/web-connect/src/features/checkout/components/ActionSection.tsx
Readded previously existing choose currency row and Crossmint checkout with credit card functionality.
Tested locally.  Local testing did not work with the current project Id and collection Id in the config. When I replaced with the original dev project Id that I created it works. So we need to confirm the config file project Id and collection Id.
=> Add back choose currency row and Crossmint Checkout

infrastructure/smart-contracts/contracts/upgrades/referee/Referee10.sol, infrastructure/smart-contracts/test/utils/getWinningKeyCountLocal.mjs, packages/core/src/operator/operator-runtime/getWinningKeyCount.ts
Update boost factor calculation in referee to fix bug for staking amount calculations.
Also, updated both local implementations of getWinningKeyCount to match the on chain logic.
=> Fix Referee Boost Factor Bug

infrastructure/smart-contracts/contracts/drops/TinyKeysAirdrop.sol, infrastructure/smart-contracts/test/NodeLicenseTinyKeys.mjs
[Ticket](https://app.shortcut.com/ex-populus/story/6336/smart-contract-tinykeyaidrop)
* Updated the `processAirdropSegmentOnlyStake` function to process up to 200 keys.
* Updated tests to reflect changes
Tested by running the test suite and observing successful results:
```
Fixture Tests
Node License Tiny Keys
Deploying Infrastructure
✔ Check the max supply is 50,000 (3421ms)
✔ Check creating and removing an address promo code
✔ Check all tiers were uploaded properly and the pricing tiers length is correct (114ms)
✔ Check minting an NFT and receiving it with ETH
✔ Check minting an NFT and receiving it with Xai (57ms)
✔ Check minting with Xai using a string promo code and receiving the correct funds (69ms)
✔ Check minting with esXai using an address promo code and receiving the correct …
```
=> TK Airdrop Contract Improvements

infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol, infrastructure/smart-contracts/test/NodeLicenseTinyKeys.mjs
[Logic Ticket](https://app.shortcut.com/ex-populus/story/6341/smart-contract-nodelicense-editable-wallet-address-for-promo-codes)
[Tests Ticket](https://app.shortcut.com/ex-populus/story/6414/tests-nodelicense-editable-wallet-address-for-promo-codes)
* Updated NodeLicense8 contract to update the promo code receiver for a client.
* Refactored to fix contract size requirements.
* Updated test to reflect changes.
```
Fixture Tests
Node License Tiny Keys
Deploying Infrastructure
✔ Check the max supply is 50,000 (2791ms)
✔ Check creating and removing an address promo code
✔ Check all tiers were uploaded properly and the pricing tiers length is correct (90ms)
✔ Check minting an NFT and receiving it with ETH
✔ Check minting an NFT and receiving it with Xai
✔ Check minting with Xai using a string …
```
=> Edit NodeLicense promo codes

infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense7.sol, infrastructure/smart-contracts/scripts/upgradeNodeLicense.mjs
[sc-6506]
Temporarily disable mint on the current NodeLicense.
Update the upgrade script to redeploy the NodeLicense7.
=> Disable mint on current NodeLicense

apps/web-connect/src/features/hooks/contract/useContractWrites.ts, infrastructure/smart-contracts/.openzeppelin/unknown-421614.json, infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol, infrastructure/smart-contracts/test/NodeLicenseTinyKeys.mjs, packages/core/src/abis/NodeLicenseAbi.ts
Update the keysale page to work with new param.
Update the ABI in core.
Extended the existing testcase to check if mint to a different address will increate the correct balance.
All tests passed as expected.
Deployed the fix to sepolia NodeLicense and tested minting with keysale page locally as well as on arbiscan.
=> Add receiver address for mintWithXai

infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense9.sol, infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol, infrastructure/smart-contracts/scripts/tiny-keys/step2.mjs, infrastructure/smart-contracts/scripts/tiny-keys/step4.mjs, infrastructure/smart-contracts/scripts/tiny-keys/step5.mjs
[sc-6664]
[sc-6663]
Remove set mintingPaused on finishAidrop, should only enable staking / unstaking keys.
Add NodeLicense9 with reinitializer setting mintingPaused to false, enabling minting.
Update Airdrop process scripts to auto refund wallets and send stats in slack.
=> Leave mintPaused after TK finish airdrop

infrastructure/smart-contracts/hardhat.config.cjs, infrastructure/smart-contracts/test/FixtureAuditTest.mjs, infrastructure/smart-contracts/test/tinykeys/RefereeBulkSubmissionTransfers.mjs
Added a new fixture where address4 stakes V1 between referee4 & 5 upgrades. This fixture was an exact copy of the original fixture.
Added new test file to test new audit fixes.
All tests pass except Gas Subsidy unrelated.
=> Added tests for Node License Transfers Bulk Submissions

apps/web-connect/src/assets/pagecontent/de.json, apps/web-connect/src/assets/pagecontent/en.json, apps/web-connect/src/features/checkout/Checkout.tsx, apps/web-connect/src/features/checkout/components/ChooseCurrencyRow.tsx, apps/web-connect/src/features/checkout/components/ChooseQuantityRow.tsx, apps/web-connect/src/features/checkout/components/LogoColumn.tsx, packages/ui/src/rebrand/steppers/MainStepper.tsx
Updated Sentry Key Sale Page copy.
Updated new content on Sentry Key Sale Page
- Added new entries to translation files
- Updated background color to match the design
- Updated min width/height to prevent page jumping on QTY change
- Updated Z-Index of a few fields that were appearing above the menu on scroll
- Fixed tooltip bug
- Added right margin on large screens to prevent qty selector from overflowing
- Fixed border color for Main Stepper component(this was not a known issue until the bg color was updated)
Tested locally by starting and confirming the page appearance in multiple screen sizes.
=> Update Sentry Page Copy

apps/web-connect/src/features/checkout/components/ActionSection.tsx
Fix Crossmint bug when minting with promo code.
Applied discount to the final price if applicable.
Tested locally by starting and minting with a promo code.
=> Fix Bug for Crossmint USDC Price with Promo Code

apps/web-connect/src/assets/pagecontent/de.json, apps/web-connect/src/assets/pagecontent/en.json, apps/web-connect/src/features/checkout/components/ActionSection.tsx, apps/web-connect/src/features/hooks/contract/useMintBatch.ts, packages/core/src/config.ts
Remove max mint batch size from config in favor of declaring in the hook and exporting.
Update translate files to accept variable in case the value needs to change.
=> Bug - Fix Crossmint Button Disabled State

apps/web-staking/src/app/components/constants/constants.ts, apps/web-staking/src/app/components/createPool/StakePoolKeyComponent.tsx, apps/web-staking/src/app/components/stakeKeysComponent.tsx/StakeKeysDetailReviewComponent.tsx, apps/web-staking/src/app/components/stakeKeysComponent.tsx/StakingKeysDetailComponent.tsx, apps/web-staking/src/app/components/staking/StakeKeyForPoolComponent.tsx, apps/web-staking/src/app/components/summary/SummaryComponent.tsx, apps/web-staking/src/assets/abi/PoolFactoryAbi.ts, apps/web-staking/src/services/web3.writes.ts, infrastructure/smart-contracts/.openzeppelin/unknown-421614.json, infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol, packages/core/src/abis/PoolFactoryAbi.ts
Add function for allowing stake and unstake with keyids
Update the staking app to use the new function
=> Add PoolFactory stake and unstake without keyIds

apps/web-connect/src/assets/pagecontent/de.json, apps/web-connect/src/assets/pagecontent/en.json
Update content on keysale tooltip
=> Fix Tooltip Text Content

apps/web-connect/src/features/hooks/web-buy-keys/useWebBuyKeysOrderTotal.ts
Fix listener to refresh allowance after approval transaction so the button state is updated.
=> Fix Approve Button Listener

apps/web-connect/src/features/checkout/components/crossmint/CrossmintModal.tsx
=> fix usdc price

apps/web-connect/src/features/hooks/contract/useContractWrites.ts, apps/web-connect/src/features/hooks/contract/useMintBatch.ts
Add Padding to Xai Price for Mint With Xai
=> Add Padding to Xai Price for Mint With Xai

apps/web-connect/src/features/checkout/components/ActionSection.tsx
=> Pause Crossmint

apps/cli/src/commands/operator-control/operator-runtime.ts
This is to show staked pools on startup for allowlist in the operator runtime cli
=> Re add staked pools on startup for allowlist

infrastructure/smart-contracts/README.md, infrastructure/smart-contracts/scripts/prepareUpgrade.mjs, infrastructure/smart-contracts/scripts/utils/getUpgradeTransactionData.mjs, pnpm-lock.yaml
Add example script for prepare upgrade and get encoded call data.
Extend readme for deployment steps on multisig
=> Add doc and sample deploy upgrade with multisig

infrastructure/smart-contracts/scripts/transfer-staked-keys/prepare-upgrade-contracts.mjs
Add script for multisig upgrade call prepare deploy new implementation and verify
=> Add prepare transfer staked keys upgrade

infrastructure/xai-governance-contracts/.openzeppelin/unknown-421614.json, infrastructure/xai-governance-contracts/contracts/XaiVoting2.sol, infrastructure/xai-governance-contracts/scripts/prepareUpgrade.mjs, infrastructure/xai-governance-contracts/scripts/utils/getUpgradeTransactionData.mjs
Add ERC20 standard functions.
Remove weight calcualtion as all the balance has the same weight.
Upgraded on sepolia
https://sepolia.arbiscan.io/address/0x415777DeB21bde51369F2218db4618e61419D4Dc#readProxyContract
=> Update XaiVoting for ERC20 compliance
