- infrastructure/smart-contracts/contracts/staking-v2/StakingPool.sol
While resetting the share timestamp & pending share values isn't technically required to get the functionality working, since the frontend will want to know if there are pending updates, at the minimum the timestamp must be reset, so I thought for the sake of keeping the contract state "clean" that we should reset the timestamp AND the pending share changes
> implement pending shares waiting period

- infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol
- infrastructure/smart-contracts/contracts/staking-v2/StakingPool.sol
- infrastructure/smart-contracts/contracts/staking-v2/Utils.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol
bugfix referre unstakeKeys, update poolinfo readfunctions, add refere…e function to get available keys of user
- Fix bug on unstake key, key still assigned in Referee
- Add Poolfacotry check for last key of owner cannot be unstaked
- Split the getPoolInfo from user data
- Add Referee function to return unstaked key ids of user with offset and page
- change index based pool interaction to address
- Remove redundant read functions from factory
- getPoolBaseInfo() still not executing in contract
> Refactory pool info read functions

- infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol
Added logic for approving/removing approval of the pool owner to operate the staking user's keys when the staking user stakes/un-stakes. Also re-ordered arguments in the stakeKeys function because i though it was cleaner if the `pool` & `poolOwner` arguments were sequential
> Fb operator control 187047289

- infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee5.sol
- Remove redundant check stakingPool.isUserEngagedWithPool
- This would always be true after doing pool.stake
- Add view to validateShareValues
- Remove unused userPoolInfo internal function
- Move valid operator check outside _submitAssertion for skipping on batch submit
All testcases and size cmd ran without errors
> Minor merge / update fixes

- infrastructure/smart-contracts/contracts/staking-v2/PoolFactory.sol
Fixed Bug array out of bounds
For example:
Alice stakes into pool A and B:
userToInteractedPoolIds[Alice][A] = 0;
userToInteractedPoolIds[Alice][B] = 1;
interactedPoolsOfUser[Alice] = [A, B];
When Alice exits from A:
userToInteractedPoolIds[Alice][A] = 0;
userToInteractedPoolIds[Alice][B] = 1; (* this is not correct)
interactedPoolsOfUser[Alice] = [B];
Now, Alice cannot exit from B due to the out-of-index issue.
> fix bug save swapped pool index on removeUserFromPool

- infrastructure/smart-contracts/test/Referee.mjs
The testcase failed because we pushed 24 tiers to the test tiers to check, probably because the first initial value was added later on.
Making the for loop only pushing 22 tiers and one initial tier will make the testcase pass.
> fix tier out of bounds error on calculate emission and tier

- apps/cli/src/commands/boot-challenger.ts
Fixing the double submit followed by Referee Error 9.
When the websocket closes and automatically reconnects, we only get the error event on close once in the runtime.
Then if the websocket ran successfully until the next node event we would first look for a missed assertion, post that and then try to submit again with the regular `onAssertionConfirmedCb`.
We actually need the challenger to catch missed assertions in between websocket reconnects. The websocket will wait 1 second to automatically reconnect, so we should wait 1 second and then call `processMissedAssertions()`.
We want to do this on any error callback from the websocket, so we make sure we don't miss an assertion from in between errors.
To not stack multiple processMissedAssertions calls we added a lock making sure it runs …
> Fix challenger double submit #187505766

- apps/cli/src/commands/operator-control/operator-runtime.ts
- packages/core/src/data-centralization/updatePoolInDB.ts
- packages/core/src/operator/operatorRuntime.ts
- packages/core/src/subgraph/getLatestChallengeFromGraph.ts
- packages/core/src/subgraph/getPoolInfosFromGraph.ts
- packages/core/src/subgraph/getSentryKeysFromGraph.ts
- packages/core/src/subgraph/getSentryWalletsForOperator.ts
- packages/core/src/subgraph/getSubgraphHealthStatus.ts
- packages/core/src/subgraph/index.ts
This will make the oeprator fallback to the RPC should the graph status not be healthy anymore.
This will also add a delay so that not all oeprators query the graph exactly at the same time when the challenge event gets emitted.
> Fb fallback rpc

- apps/sentry-client-desktop/src/features/drawer/WhitelistDrawer.tsx
- apps/sentry-client-desktop/src/hooks/useOperatorRuntime.ts
For https://www.pivotaltracker.com/story/show/187692037
Fix the race condition and prevent overwrite from file cache in the desktop app.
> Desktop Client: Prevent overwrite of local file cache with default values 

- apps/cli/src/commands/export-challenge-info.ts
- apps/cli/src/index.ts
- infrastructure/sentry-subgraph/generated/schema.ts
- infrastructure/sentry-subgraph/schema.graphql
- infrastructure/sentry-subgraph/schema/events/Referee.graphql
- infrastructure/sentry-subgraph/src/referee.ts
- packages/core/src/subgraph/getChallengesFromGraph.ts
- packages/core/src/subgraph/index.ts
For https://www.pivotaltracker.com/story/show/187606168
This has the udpated subgraph syncing script with the submittedFrom and claimedFrom fields to every submission.
Subgraph is currently syncing (v 1.1.10)
https://subgraphs.alchemy.com/subgraphs/4740/versions/19992
Once the subgraph is synced, the export script can be run with the updated subgraph endpoint for the extended challenge info
> Fb export from graph

- apps/web-staking/src/app/components/redeem/History.tsx
Copy from https://github.com/CryptITAustria/sentry/pull/53
Added clearing of isCancel state after useWaitForTransactionReceipt returns new isSuccess state. Also removed isCancel state from updateOnSuccess dependecies array to avoid incorrect notifications.
task: https://www.pivotaltracker.com/story/show/187790660
> fix: fixed reedem cancel button

- apps/web-connect/src/features/checkout/Checkout.tsx
- apps/web-staking/src/app/components/modal/MessageModalComponent.tsx
- apps/web-staking/src/app/components/modal/MintSuccessfulComponent.tsx
- apps/web-staking/src/app/components/staking/StakingOverviewComponent.tsx
[Ticket](https://www.pivotaltracker.com/n/projects/2671427/stories/187742143)
sentry.xai.games: After successful mint a new tab redirects to app.xai.gaming/staking page with query param
app.xai.gaming/staking: On page check of query param open a modal with a message and a close button
Added new reusable MessageModal, as old modals had old styles
> Fb tiny keys redirect

- packages/core/src/subgraph/getRewardRatesFromGraph.ts
For https://www.pivotaltracker.com/story/show/187862171
Update the rewards calculation to not average by historic staked data from the pool challenge.
I added a TODO to refactor the calculation for efficiency.
Currently this won't make any significant difference, however when we get to having more than 1000 pools this can make a bigger difference.
Tested by manually syncing rewards for mainnet into dev db, now add up to manual calculation from onchain data
> Remove average to staked amounts from historic challenge data

- apps/cli/src/commands/operator-control/operator-runtime.ts
- packages/core/src/operator/operatorRuntime.ts
For https://www.pivotaltracker.com/n/projects/2671427/stories/187837196
If the operator wallet does not have any reference on the subgraph we would currently load all the keys from all pools we get in one subgraph query. This resulted in the desktop app running for 8K keys by default on a fresh install.
Also fixes the whitelist feature in the cli for the same reasons.
> fix operator runtime bug loading all pools on start

- apps/sentry-client-desktop/src/index.css
For some reason our checkbox component doesn't work properly on desktop-operator (tailwind opacity classes don't apply at all). I tested it on web-connect and staking - it works. So to avoid any changes for global UI components - i did changes only for dekstop-operator index.css
[Ticket](https://www.pivotaltracker.com/n/projects/2671427/stories/187891849)
> Fix checkbox checked view

- infrastructure/sentry-subgraph/schema.graphql
- infrastructure/sentry-subgraph/schema/events/PoolFactory.graphql
- infrastructure/sentry-subgraph/schema/events/Referee.graphql
- infrastructure/sentry-subgraph/src/referee.ts
- packages/core/src/operator/operatorRuntime.ts
https://www.pivotaltracker.com/story/show/187742159
Remove KYC check on claim from Operator Runtime(Core) and sub-graph.
Notes:
Subgraph removal required referee version checking.
Added the https://github.com/Index param to a few graphQL fields to improve query speeds.
New subgraph deployed and syncing here: https://subgraph.satsuma-prod.com/xai/sentry/version/v1.1.14/api
> Remove KYC From Operator & Sub-graph on claim

- infrastructure/smart-contracts/test/stakingv2/SubmittingAndClaiming.mjs
- infrastructure/smart-contracts/test/stakingv2/VerifyBoostFactor.mjs
For: https://www.pivotaltracker.com/story/show/187870055
- updates to tests that depend on `_submitAssertion()`, `claimReward()`, or `claimMultipleRewards()`
- could not be tested yet due to latest referee contract size issues
- tests are likely to be broken because of randomness of poolSubmissions
> Testcase: Update Referee testcases for all existing tests

- infrastructure/sentry-subgraph/schema/events/Referee.graphql
- infrastructure/sentry-subgraph/src/referee.ts
Task: https://www.pivotaltracker.com/n/projects/2671427/stories/187869828
- Add new entity for poolSubmission
- Add new events UpdatePoolSubmissionEvent, NewPoolSubmissionEvent, PoolRewardsClaimedEvent
- Did not update existing events: As in updated contract assigned keys do not trigger the events
- [Blocker] upgrade referee not deployable as to big, cannot get event signature
Answered Questions from task:
additional fields: claimed, createdTimestamp, claimTimestamp, createdTxHash, claimTxHash, sentryKey, challenge
Would consider an additional task for the queries, as currently there is no synced graph to test
> Fb tiny keys subgraph pool submissions

- infrastructure/smart-contracts/contracts/tiny-keys/RefereeGetWinningKeyCount.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee9A.sol
https://www.pivotaltracker.com/story/show/187900698
Removed setters to improve contract size.
Also, had to comment out an incorrect param in getWinningKeyCount function to get the contracts to compile.
Contract size after removing setters is 25.136kb
> Remove setters to improve contract size

- infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee9A.sol
https://www.pivotaltracker.com/story/show/187900838
https://www.pivotaltracker.com/story/show/187900825
Moved key staking logic from Referee to Pool Factory. 
Note, I did not move the stake/unstake esXai to Pool Factory as they are only 2 line functions.
> Move Key Stake Functions to Pool Factory

- packages/core/src/operator/claimPoolSubmissionRewards.ts
- packages/core/src/operator/index.ts
- packages/core/src/operator/operatorRuntime.ts
- packages/core/src/operator/submitPoolAssertions.ts
https://www.pivotaltracker.com/story/show/187869847
https://www.pivotaltracker.com/story/show/187869544
1. Added functions to core for submitPoolAssertions & claimPoolSubmissionRewards.
2. Called those two methods in the operator runtime in the processNewChallenge callback.
Still need to create stories around:
1. Updating the Graph/RPC queries to only return un-staked keys.
2. Update the Graph/RPC queries to return the pools that the operator should operate on.
> Added Pool Submission and Pool Claim

- infrastructure/smart-contracts/contracts/upgrades/esXai/esXai3.sol
- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
- infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol
- infrastructure/smart-contracts/test/Fixture.mjs
- infrastructure/smart-contracts/test/failed-kyc/FailedKyc.mjs
https://www.pivotaltracker.com/story/show/187862702
Added failed KYC variable to pool factory.
If preferred, I can move the variable to the esXai contract and have the poolFactory check the esXai contract instead.
I chose not to include the variable in the referee due to size issues.
Note, had to remove ReentrancyGuard from NodeLicense to get tests to run. Those changes were in another PR [#301](https://github.com/xai-foundation/sentry/pull/301) but also included here
> Added Failed KYC Requirements

- apps/web-staking/src/app/components/AnnouncementBanner.tsx
- apps/web-staking/src/app/components/navbar/WrapperComponent.tsx
- apps/web-staking/src/app/globals.css
For https://www.pivotaltracker.com/story/show/187849510
Adding an announcement banner to the staking app.
Can be controlled from the wrapper component.
> add announcement banner for staking app

- infrastructure/smart-contracts/contracts/RefereeCalculations.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
- infrastructure/smart-contracts/test/tinykeys/RefereeBulkSubmissions.mjs
- infrastructure/smart-contracts/test/utils/getWinningKeyCountLocal.mjs
- packages/core/src/operator/operator-runtime/getWinningKeyCount.ts
For https://www.pivotaltracker.com/story/show/188108692
Add the mainnet configs to the Referee initialize.
Update the boostFactor to support 4 decimals, setting the base chance to 0.01 % (Silver tier => 0.015%)
> Update boostfactor to support 4 decimals, update base chance to 0.01%

- apps/web-staking/src/app/IpLocationChecker.tsx
For https://www.pivotaltracker.com/story/show/188143506
Update the formatting of the `IpLocationChecker` when blocked.
Tested locally by manually setting `setBlocked(true)` to trigger the IP block.
Checked position and formatting on desktop & mobile
> fix position and formatting of restriced IP text

- packages/core/src/operator/operator-runtime/bootOperatorRuntime.ts
- packages/core/src/operator/operator-runtime/listenForChallengesCallback.ts
- packages/core/src/operator/operator-runtime/operator-v1/bootOperatorRuntime.ts
- packages/core/src/operator/operatorRuntime.ts
- packages/core/src/utils/resilientEventListener.ts
[Ticket](https://www.pivotaltracker.com/story/show/187985681)
* Updated Websocket and JSON RPC health check frequency to every 15 minutes.
* Updated language in the operator runtime logs to explain that challenges should occur roughly once per hour, but delayed challenges will not fail to accrue rewards.
Tested by running the `boot-operator` in the cli and observing the updated logs and health check frequency.
> Updated Operator Logs and Health Check Frequency

- infrastructure/sentry-subgraph/abis/Rollup.json
- infrastructure/sentry-subgraph/schema.graphql
- infrastructure/sentry-subgraph/schema/events/Referee.graphql
- infrastructure/sentry-subgraph/sepolia.subgraph.yaml
- infrastructure/sentry-subgraph/src/referee.ts
- infrastructure/sentry-subgraph/src/utils/updateChallenge.ts
- infrastructure/sentry-subgraph/subgraph.yaml
[Ticket](https://www.pivotaltracker.com/story/show/187992525)
* Added `NodeConfirmation` entity to subgraph schema.
* Updated Challenge entity to reference one or more `NodeConfirmation` entities.
* Added event handler for `NodeConfirmed` events.
* Updated Challenge handler to populate the new `nodeConfirmations` field with one or more `NodeConfirmation` entities.
Tested by querying for both the Challenge and NodeConfirmation entities in the subgraph [here](https://subgraph.satsuma-prod.com/xai/sentry/version/1.1.21/playground)
Test Queries:
NodeConfirmations
```
query MyQuery {
nodeConfirmations(first: 5) {
id
nodeNum
confirmData
}
}
```
Challenges
NOTE: we skip early challenges because they won't have an associated nodeConfirmation
```
query MyQuery {
challenges(orderBy: …
```
> Subgraph ConfirmData

- infrastructure/sentry-subgraph/generated/schema.ts
- infrastructure/sentry-subgraph/schema.graphql
- infrastructure/sentry-subgraph/schema/events/PoolFactory.graphql
- infrastructure/sentry-subgraph/schema/events/Referee.graphql
- infrastructure/sentry-subgraph/src/node-license.ts
- infrastructure/sentry-subgraph/src/pool-factory.ts
- infrastructure/sentry-subgraph/src/referee.ts
- infrastructure/sentry-subgraph/src/utils/updateTotalAccruedRewards.ts
For https://www.pivotaltracker.com/story/show/188210182
Adding a new field `totalAccruedAssertionRewards` to the SentryWallet and PoolInfo entities.
This will be used to display the total accrued rewards in the desktop app without having to fetch each submission for each key.
Subgraph deployed and currently syncing:
- Mainnet: https://subgraphs.alchemy.com/subgraphs/4740/versions/26457
- Testnet: https://subgraphs.alchemy.com/subgraphs/6221/versions/26456
> Add totalAccruedAssertionRewards to subgraph

- apps/sentry-client-desktop/electron/main.ts
- apps/sentry-client-desktop/src/components/AssignKeysFromNewWallet.tsx
- apps/sentry-client-desktop/src/components/InfoBanner.tsx
- apps/sentry-client-desktop/src/features/drawer/ActionsRequiredPromptHandler.tsx
- apps/sentry-client-desktop/src/features/drawer/WhitelistDrawer.tsx
- apps/sentry-client-desktop/src/features/home/SentryWallet.tsx
- apps/sentry-client-desktop/src/features/home/SentryWalletHeader.tsx
- apps/sentry-client-desktop/src/features/home/SentryWalletTableBody.tsx
- apps/sentry-client-desktop/src/features/home/modals/RemoveWalletModal.tsx
- apps/sentry-client-desktop/src/features/keys/HasKeys.tsx
- apps/sentry-client-desktop/src/features/keys/Keys.tsx
- apps/sentry-client-desktop/src/hooks/useGetOperatorAddresses.ts
- apps/sentry-client-desktop/src/hooks/useOperatorRuntime.ts
- packages/core/src/operator/operator-runtime/loadOperatorWalletsFromGraph.ts
- packages/core/src/operator/operator-runtime/processNewChallenge.ts
- packages/core/src/subgraph/getSentryWalletDataFromGraph.ts
- packages/core/src/subgraph/index.ts
- packages/ui/src/rebrand/icons/IconsComponents.tsx
For https://www.pivotaltracker.com/story/show/188182849
This is building on top of https://github.com/xai-foundation/sentry/pull/414
Update the sentry wallet page view, update the calculations for wallets and key counts.
I had to rework the add/remove wallet logic as well as the assign wallet logic as this was used across keys and sentry wallet page but does not make any sense anymopre when showing only wallets/pools.
Tested locally running on sepolia config.
Started from clean with a fresh wallet, tested the whole "new user" flow.
Imported multiple wallets to test userflow for different operator status.
Additional update logs for https://www.pivotaltracker.com/story/show/188218469
Additional updates from previous PR
- Rename subgraph function …
> Operator desktop client update sentry wallet page 

- packages/core/src/operator/getConfirmDataAndHash.ts
- packages/core/src/operator/index.ts
- packages/core/src/subgraph/getConfirmDataFromGraph.ts
- packages/core/src/subgraph/index.ts
- packages/core/src/utils/getMultipleChallengeConfirmData.ts
[ticket](https://www.pivotaltracker.com/story/show/187985809)
* Added the `getConfirmDataFromGraph` function and added to the subgraph index file.
* Added the top-level `getConfirmDataAndHash` function to fetch confirm data from graph or RPC.
* Added missing parameter in `getConfirmDataMultipleAssertions` RPC function.
Tested by adding the new function calls to a CLI command (testing changes not committed for this PR). Both subgraph and the RPC fallback paths were tested successfully.
Added to `total-supply.ts` to trigger the function call:
```
try {
let res = await getConfirmDataAndHash([1, 2, 3], true);
this.log(`>>> TESTING: confirmData: ${res.confirmData} confirmHash: ${res.confirmHash}`);
} catch (error) {
this.log(`Error: ${error}`);
}
```
Also updated the `config.ts` as follows: …
> Operator Load Confirm Data

- apps/web-staking/src/app/components/summary/SummaryComponent.tsx
- apps/web-staking/src/app/components/summary/SummaryUnstakingItem.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188167558)
Fixed requests being removed from local storage before tx has succeeded.
After a successful tx, the `isSuccess` state variable was not being reset, this allowed any subsequent txs to have the request removed from local storage regardless if the tx was successful. 
Fixed by resetting the tx receipt after each successful tx which resets the isSucces state in the hook.
Note: claim button for cancelled claim remains disabled after cancelation until refresh/clicking off page and back. Fixing that would require refactoring the button state outside of the component.
Tested locally and deployed on [develop here](https://develop.app.xai.games/).
> Bug Fix: Staking App: Unstake request disappears on claim error

- .github/workflows/release.yml
- .github/workflows/test-release.yml
- Dockerfile
For https://www.pivotaltracker.com/story/show/187983657
Add credential id argument to signer.
Update the signer action to the non depricated version.
Credentials were set correctly however the secret key got blocked for to many invalid attempts, see more context in the ticket.
Additionally updated the staking app Dockerfile for enabling the dev env build args
Waiting for the services team update to fix setting the docker build args - deployment to develop with the updated Dockerfile currentl fails
> fix: add credential id for windows signing

- .dev-deploy/docker-compose.yml
- .dev-deploy/web-connect.Dockerfile
- .dev-deploy/web-staking.Dockerfile
- .github/workflows/pr-close.yaml
- .github/workflows/pr-review.yaml
For https://www.pivotaltracker.com/story/show/188187038
This update adds github actions trigger to deploy dynamic dev environments for web-staking and web-connect.
These jobs will run on a self hosted github runner on a host setup with docker and a nginx proxy to route 
The triggers are setup to deploy on PR request review, PR approved and cleanup on PR close.
> Add dev deploy CICD

- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
- infrastructure/smart-contracts/contracts/xai-subsidy/Forwarder.sol
- infrastructure/smart-contracts/test/Fixture.mjs
- infrastructure/smart-contracts/test/NodeLicenseTinyKeys.mjs
[Ticket](https://www.pivotaltracker.com/story/show/188332927)
Updated NodeLicense contract by adding a new mintTo function that allows the minter to pass in the address that the license should be minted to.
Testing: tested with test cases. Also deployed on [Sepolia here ](https://sepolia.arbiscan.io/address/0x07C05C6459B0F86A6aBB3DB71C259595d22af3C2).
Completed a test using mintTo on Sepolia and confirmed the recipient received the license via [this transaction](https://sepolia.arbiscan.io/tx/0x4e39ada9bc9141c37cb1fae3b66f860471f1db4d86c9e2f6d0244f43ba269680).
> Add mintTo Function to Node License Contract.

- infrastructure/smart-contracts/contracts/RefereeCalculations.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
- infrastructure/smart-contracts/package.json
[Ticket](https://www.pivotaltracker.com/story/show/188311132)
Updated referee calculations to calculate emission using the previous calculation with no changes. 
Then updated the referee to calculate the time passed since last challenge and then determine the total emissions for the challenge based on the amount of time passed. 
Testing: tested, by confirming all Referee tests still pass. Also deployed on Sepolia and used the explorer to confirm the functions work as expected.
Made adjustments to meet story requirements. 
I confirmed all Referee tests still pass(minus two that were already failing and are being fixed in another story), and I redeployed on Sepolia and confirmed the calculateChallengeEmissionAndTier works as expected.
Additional revisions made to revert changes to …
> Updated Referee to manage emissions calculations in the referee

- apps/web-staking/src/app/components/navbar/WrapperComponent.tsx
- apps/web-staking/src/app/components/pool/MyPoolComponent.tsx
- apps/web-staking/src/app/components/redeem/History.tsx
- apps/web-staking/src/app/hooks/index.ts
- apps/web-staking/src/app/hooks/useGetKYCApprovedForRedemptionClaim.ts
- apps/web-staking/src/app/staking/page.tsx
- apps/web-staking/src/server/services/Pool.service.ts
- apps/web-staking/src/services/web3.service.ts
For [#188413859](https://www.pivotaltracker.com/story/show/188413859)
Comment out KYC check for before contract upgrade.
Readd function for Referee KYC check used on pool create.
For [#188456707](https://www.pivotaltracker.com/story/show/188456707)
Add additional `_id` on sort for pools table to preserve consistent order across pages
Tested locally running `pnpm staking-preview`, verified KYC not required for claim redemption & create pool. 
Tested staking pool order on prod mainnet pools.
> Prepare stakingapp pre upgrade, fix staking pool list order

- apps/cli/src/commands/boot-challenger.ts
- apps/cli/src/index.ts
- packages/core/src/challenger/findMissedAssertion.ts
- packages/core/src/challenger/isChallengeSubmitTime.ts
- packages/core/src/config.ts
- packages/core/src/constants/constants.ts
- packages/core/src/constants/index.ts
- packages/core/src/index.ts
For [#188385836](https://www.pivotaltracker.com/story/show/188385836)
Add dev cli command to toggle network switch: `toggle-switch-network`
Moved min seconds between challenges constant to config so it can be changes for testnet tests.
Increase loopCount for finding missed assertions, this will return undefined if too many blocks have passed until the latest NodeConfirmed. On testnet after about 10 hours, mainnet will have more blocks passing so this will be a shorter time.
Tested locally, added dev logs to print current config, tested toggle between mainnet and testnet and run commands in between to confirm toggle works.
Built locally and testent challenger and operator on testnet mode while confirming nodes on mockrollup.
> Add network toggle switch command to cli runtime

- infrastructure/sentry-subgraph/src/pool-factory.ts
[Ticket](https://www.pivotaltracker.com/story/show/188505303)
Added `toLowerCase` to addresses for querying. Only added for portions of the code showing error logs. 
Will monitor logs and add in additional locations if needed. 
Leaving in draft until the [graph here](https://subgraph.satsuma-prod.com/xai/sentry/version/1.2.3/playground) has synced successfully without warnings. 
Logs still show warnings but only for claims from a user who created a custom claim contract. All other warnings have been resolved.
> Fix Subgraph Handlers Case MisMatch

- apps/sentry-client-desktop/electron/main.ts
- apps/sentry-client-desktop/src/features/sidebar/SidebarRoot.tsx
- apps/sentry-client-desktop/src/hooks/useChainDataWithCallback.ts
- packages/core/src/config.ts
For [#188385835](https://www.pivotaltracker.com/story/show/188385835)
Extend Electron menu View with dev option to toggle network switch.
This will display Testnet on the Sidebar.
Not all blockchain state will automatically refresh, like balance or operatorRuntime, these need to be refreshed manually by clicking the refresh button/link. 
Refreshing the app windows will return to default mainnet state.
Tested with lcoal dev and release build.
Press `ALT` to trigger the App menu, under `View` click `[DEV] Network switch`. This will enable the sepolia config in the app.
> Add toggle network switch to electron menu

- apps/web-staking/src/app/components/navbar/NavbarComponent.tsx
- apps/web-staking/src/app/components/navbar/SidebarComponent.tsx
- apps/web-staking/src/app/components/staking/TableChunksComponents.tsx
[Ticket](https://www.pivotaltracker.com/story/show/188513584)
Fixed progress bar that was missing by updating the css.
Pending fix for menu being full width on mobile.
Tested locally and on PR link. On PR link there's currently no data to show the progress bar, but the mobile menu works on the PR link.
Fixed mobile menu close button (X) movied it back to the correct position (top right). Created a toggle handler function with a small delay to prevent unintentional clicks when the hamburger button is clicked.
> Fix staking progress bar

- infrastructure/smart-contracts/contracts/upgrade-tests/NodeLicenseUpgradeTest.sol
- infrastructure/smart-contracts/hardhat.config.cjs
- infrastructure/smart-contracts/test/Fixture.mjs
- infrastructure/smart-contracts/test/NodeLicense.mjs
For [#188548399 ](https://www.pivotaltracker.com/story/show/188548399)
Add tests for adminMinTo.
Updated the fixture to upgrade to TK contracts.
Update hardhat config to add storageLayout to artifacts output for testing with altered state.
Tested locally, including not reverting in the nodeLicense Functions to run the full test code.
Only test that passes checks for the required access control role
```
✔ Checks calling adminMintTo without ADMIN_MINT_ROLE will fail (38ms)
1) Checks that the admin can mint to a receiver without fee
2) Should not allow the admin to mintTo past the maxSupply
```
> Add tests for NodeLicense Admin minTo

- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
For [#188548397](https://www.pivotaltracker.com/story/show/188548397)
Add implementation for `adminMintTo`
Ran test from https://github.com/xai-foundation/sentry/pull/481, all passed.
```
✔ Checks calling adminMintTo without ADMIN_MINT_ROLE will fail (44ms)
✔ Checks that the admin can mint to a receiver without fee
✔ Should not allow the adminMintTo to exceed the maxSupply
```
> Implement admin mintTo function

- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
For [#188548411](https://www.pivotaltracker.com/story/show/188548411)
Add transferFrom & safeTransferFrom overwrite to allow transfer with `TRANSFER_ROLE`
Tested locally against the tests from https://github.com/xai-foundation/sentry/pull/484
```
✔ Should require TRANSFER_ROLE for any transfers (116ms)
✔ Should allow safeTransferFrom with TRANSFER_ROLE (54ms)
✔ Should allow transferFrom with TRANSFER_ROLE (46ms)
✔ Should allow adminTransferBatch with TRANSFER_ROLE (46ms)
✔ Should revert transfer of a token not owned by sender (67ms)
✔ Should allow transferFrom with approval (38ms)
✔ Should revert adminTransferBatch using the same transferId (48ms)
```
Additionally ran the whole test suite, everything is passing as expected.
> Implement admin transfer allowlist

- infrastructure/smart-contracts/test/Fixture.mjs
- infrastructure/smart-contracts/test/NodeLicense.mjs
For [#188548418](https://www.pivotaltracker.com/story/show/188548418)
Add tests for allowing transfer with new role.
Update existing test for new expected revert message
Tested locally:
```
4) Should require TRANSFER_ROLE for any transfers
5) Should allow safeTransferFrom with TRANSFER_ROLE
6) Should allow transferFrom with TRANSFER_ROLE
7) Should allow adminTransferBatch with TRANSFER_ROLE
8) Should revert transfer of a token not owned by sender
9) Should revert adminTransferBatch using the same transferId
```
Additionally updated the fixture for using poolFactory2 so the TK tests will pass.
Made sure all test code will run with dummy functions within NodeLicense.
> Add tests for transfer auth

- infrastructure/smart-contracts/contracts/RefereeCalculations.sol
- infrastructure/smart-contracts/contracts/upgrade-tests/NodeLicenseUpgradeTest.sol
- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
- infrastructure/smart-contracts/scripts/tiny-keys/deployTinyKeys.mjs
- infrastructure/smart-contracts/test/Fixture.mjs
- infrastructure/smart-contracts/test/NodeLicense.mjs
For [#188577643](https://www.pivotaltracker.com/story/show/188577643) 
* Fixed NodeLicense8 contract size issue.
* Added `_refereeCalculationsAddress` param to initializer and new public `refereeCalculationsAddress` state variable.
* Commented out tests that were for functions removed by this PR.
Tested by running `pnpm test` and observing successful test results for NodeLicense:
```
✔ Check calling the initializer is not allowed afterwards
✔ Check the max supply is 50,000
✔ Check creating and removing promo codes
✔ Check all tiers were uploaded properly and the pricing tiers length is correct (100ms)
✔ Check minting an NFT and receiving it
✔ Check minting with a promo code and receiving the correct funds
✔ Check that NFTs are not transferable after minting (47ms)
✔ Check referral reward …
```
> Fix Contract Size

- infrastructure/smart-contracts/contracts/drops/TinyKeysAirdrop.sol
- infrastructure/smart-contracts/contracts/upgrade-tests/NodeLicenseUpgradeTest.sol
- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
- infrastructure/smart-contracts/scripts/tiny-keys/deployTinyKeys.mjs
- infrastructure/smart-contracts/test/Fixture.mjs
- infrastructure/smart-contracts/test/NodeLicense.mjs
- infrastructure/smart-contracts/test/utils/createPool.mjs
For [#188577671](https://www.pivotaltracker.com/story/show/188577671)
Add require key to be unstaked on NodeLicense transfer.
Add refereeAddress to NodeLicense state.
Add test for checking fail on transfer of staked key.
Update TKAirdrop for not passing refAddress anymore.
Update tk deploy script.
Ran full test suite locally.
Deployed this NodeLicense upgrade to sepolia, tested transfer manually.
> Nodelicense revert on transfer staked

- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
- infrastructure/smart-contracts/test/NodeLicense.mjs
* Added a fix for usdc decimal conversion bug.
* Updated tests to reflect changes.
Tested by running `pnpm test` and observing successful USDC test results:
```
✔ Check if can mint with USDC to recipient address
✔ Check if can mint with USDC to recipient address using a valid promo code (48ms)
✔ Check if can claim USDC referral rewards (48ms)
```
> Fix USDC Decimal Conversion Bug

- infrastructure/sentry-subgraph/abis/PoolFactory.json
- infrastructure/sentry-subgraph/generated/PoolFactory/PoolFactory.ts
- infrastructure/sentry-subgraph/sepolia.subgraph.yaml
- infrastructure/sentry-subgraph/src/pool-factory.ts
- infrastructure/sentry-subgraph/subgraph.yaml
[Ticket](https://app.shortcut.com/ex-populus/story/6190/update-subgraph-to-work-with-new-poolfactory2-events)
Update Subgraph handlers to work with new PoolFactory2 Events
Added new handlers for PoolFactoryV2 events.
Updated existing events to be ignored after PoolFactory2 is deployed.
Tested by deploying on [Sepolia](https://subgraphs.alchemy.com/subgraphs/6221/versions/31282) & [Mainnet](https://subgraphs.alchemy.com/subgraphs/4740/versions/31284). Seeded some new test events on Sepolia and confirmed they were handled.
> Update Subgraph handlers to work with new PoolFactory2 Events

- infrastructure/sentry-subgraph/src/node-license.ts
[Ticket](https://app.shortcut.com/ex-populus/story/5648/subgraph-fix-sentrykey-sync-on-transfer-from-non-zero-address)
Updated the NodeLicense transfer handler in the subgraph to handle transfer from non-zero address.
Tested by [deploying on Sepolia](https://subgraph.satsuma-prod.com/xai/sentry-sepolia/version/1.3.2-sepolia/playground) and confirming sync. Tested by [transferring a node license](https://sepolia.arbiscan.io/tx/0x421442ed8831f975aaac7529d88040cc9c6993df00db57ce123805c8ea595399) and confirming that the subgraph updated both the wallet key count and the key owner.
> Update node license transfer handler in subgraph

- infrastructure/smart-contracts/contracts/upgrade-tests/NodeLicenseUpgradeTest.sol
- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
- infrastructure/smart-contracts/test/NodeLicense.mjs
Updated Node License adminMintTo function to check tx hash to prevent duplicates.
Contract then exceeded max size, refactored a few require statements into custom errors to reduce contract size. Only changed requires in new functions or the initializer to ensure dependencies on all existing error messages remain the same.
Updated tests to confirm new function works. Confirmed all expected passing tests pass.
> NodeLicense Add transferId to adminMintTo

- infrastructure/sentry-subgraph/sepolia.subgraph.yaml
- infrastructure/sentry-subgraph/src/node-license.ts
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
[sc-6292]
[sc-6293]
Add constant to Referee.
Add check for max key id on submit assertion
Add return in subgraph ony sync Sentrywallet
Updated the sepolia subgraph config with new addresses.
Deployed to sepolia with new contract deployments from https://github.com/xai-foundation/sentry/pull/496 tagged `1.3.4-sepolia-skip-tk`
Ran test suite with Referee Upgrade, everything passed like before.
>  Add check for key id on sync subgraph and submit assertion

- .github/workflows/deploy-web-connect.yml
- apps/web-connect/vite.config.ts
- Added `base: '/'` to `vite.config.ts` for root deployment on Cloudflare Pages.
- Added `cloudflare_project` input to workflow for specifying the Cloudflare project.
- Implemented Cloudflare Pages deployment step in the GitHub Actions workflow.
- Removed the `xai-drop-permits.JSON` file before deployment.
- Updated environment variables for Cloudflare API token usage.
> fix: configure root deployment and add Cloudflare deploy

- apps/web-staking/src/app/components/createPool/StakePoolKeyComponent.tsx
- apps/web-staking/src/app/components/stakeKeysComponent.tsx/StakingKeysDetailComponent.tsx
Update staking app input validation from max 100 to max 200.
Tested locally by confirming U/I validation and by completing a [stake tx with 200 keys](https://sepolia.arbiscan.io/tx/0xadf97dc6f424e7ab8f4e79780ec4bf568f504fcb4e577f19a436a796678b0b99).
> Update max stake/unstake keys to 200 per txn

- apps/web-staking/src/app/components/createPool/StakePoolKeyComponent.tsx
- apps/web-staking/src/app/components/stakeKeysComponent.tsx/StakingKeysDetailComponent.tsx
Fix incorrect max staked keys copy.
Tested locally by starting app, confirming copy and performing an [unstake](https://sepolia.arbiscan.io/tx/0x0b32849b10b5bf3e48d1e5e5e61e30433ec112b2710e058b9f604cd45f5308df).
> Fix Staking App Max Keys per tx Copy

- infrastructure/smart-contracts/contracts/upgrades/referee/Referee10.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
- infrastructure/smart-contracts/test/NodeLicenseTinyKeys.mjs
[[sc-6413]](https://app.shortcut.com/ex-populus/story/6413/smart-contract-track-set-staking-enabled-during-tk-aidrop)
Update Aidrop testcases to check staking and unstaking during aidrop.
Fix the error code in Referee when staking disabled.
Ran testcases locally, everything passed as expected.
> Update TK process tests to check for staking and unstaking

- apps/sentry-client-desktop/src/features/keys/modals/buy-keys/BuyKeysFlow.tsx
- apps/web-connect/src/features/checkout/CheckoutWrapper.tsx
[Ticket](https://app.shortcut.com/ex-populus/story/5713/set-default-quantity-to-10)
Updated default purchase quantity of keys from 1 to 10.
Tested with default quantity on Arbitrum Sepolia [Tx Hash](https://sepolia.arbiscan.io/tx/0xbb90b526bd7bc5aba4eff1b1b9d1ebcdb812c296325ef99d351859f5ff10ee01)
> Default Key Quantity

- apps/web-connect/src/features/checkout/Checkout.tsx
- apps/web-connect/src/features/checkout/components/PurchaseSuccessful.tsx
Will link to the correct environment domain on purchase success.
Tested locally with `pnpm preview-web` with VITE_APP_ENV=develop in the local .env
> Link to correct environment for referral link

- apps/web-connect/src/features/checkout/components/AgreementCheckboxes.tsx
- apps/web-connect/src/features/footer/ReactCookieConsent.tsx
- apps/web-connect/src/features/wallet/routes/DropClaim.tsx
- apps/web-staking/src/app/components/ReactCookieConsent.tsx
- apps/web-staking/src/app/components/modal/AgreeModalComponents.tsx
Updated the broken Sentry node agreement and privacy policy links on the key sale and staking app. 
Tested locally by starting and confirming broken links now work.
> Fix Broken links on Key sale and Staking pages

- apps/web-connect/src/features/checkout/components/ActionSection.tsx
- apps/web-connect/src/features/checkout/components/AgreementCheckboxes.tsx
- apps/web-connect/src/features/checkout/components/ChooseQuantityRow.tsx
- apps/web-connect/src/features/checkout/components/PricePerKeyRow.tsx
- apps/web-connect/src/features/checkout/components/PromoCodeRow.tsx
- apps/web-connect/src/features/checkout/components/PurchaseSuccessful.tsx
- apps/web-connect/src/features/checkout/components/TotalCostRow.tsx
- apps/web-connect/src/features/wallet/routes/DropClaim.tsx
- apps/web-connect/src/features/wallet/routes/RedEnvelope2024.tsx
- apps/web-connect/src/main.tsx
Updated copy on sentry page to say Sentry Key instead of Sentry Node Key.
Tested locally by starting app and viewing new copy.
> Update copy on sentry page

- .github/workflows/pr-review.yaml
- apps/web-connect/src/features/checkout/Checkout.tsx
- apps/web-connect/src/features/checkout/components/SaleInfoModal.tsx
Adding the SaleInfoModal blocking the checkout page for info about tk sale release.
This PR is for having the test env.
We will deploy manually to cf pages to release this when business is ready.
> Add sale info modal for tk release

- infrastructure/smart-contracts/test/NodeLicense.mjs
Update the Node License tests to work with the new custom error messages that were implemented for contract size.
There will be a separate PR coming for the audit-fix tests.
Builds on top of [PR#524](https://github.com/xai-foundation/sentry/pull/524)
Can be merged into PR#524, or changed and merged separately into develop.
> Fix NodeLicense Tests Part 1

- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee10.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee9.sol
Updated NodeLicense and Referee to support updating BulkSubmissions on Transfer.
Tests coming in separate PR.
> Allow NodeLicense to update bulkSubmissions on key transfer

- apps/web-connect/src/assets/pagecontent/de.json
- apps/web-connect/src/assets/pagecontent/en.json
- apps/web-connect/src/features/checkout/Checkout.tsx
- apps/web-connect/src/features/checkout/components/ActionSection.tsx
- apps/web-connect/src/features/checkout/components/ChooseQuantityRow.tsx
- apps/web-connect/src/features/checkout/components/PurchaseSuccessful.tsx
- apps/web-connect/src/features/hooks/contract/useContractWrites.ts
- apps/web-connect/src/features/hooks/contract/useMintBatch.ts
- apps/web-connect/src/features/hooks/web-buy-keys/useWebBuyKeysOrderTotal.ts
- packages/core/src/config.ts
- packages/ui/src/features/inputs/XaiNumberInput.tsx
- packages/ui/src/rebrand/steppers/MainStepper.tsx
Update Keysale Page to support batch mints
- Added Crossmint Disabled button text to translations
- Created new hook to manage Batch Mints
- Updated sale page Transaction InProgress/Purchase Successful conditional display to include batch mint txs
- Renamed some functions for clarity
- Cleaned up buy keys hook to return merged hooks vs destructuring and returning individual properties.
- Updated ActionsSection to call different mint functions based on qty
- Added Mint Batch Error Section
- Added button validation for max crossmint qty per tx
- Updated choose quantity row css to allow for larger numbers in the input box
- Updated PurchaseSuccess page to map all minted tx hashes
- Added maxBatchMintSize to config to allow us to test with batch sizes of 2 to save test net tokens
Tested …
> Update Keysale Page to support batch mints

- apps/web-staking/src/services/web3.service.ts
- infrastructure/smart-contracts/contracts/drops/TinyKeysAirdrop.sol
- infrastructure/smart-contracts/contracts/staking-v2/StakingPool.sol
- infrastructure/smart-contracts/contracts/upgrades/StakingPool/StakingPool2.sol
- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense8.sol
- infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory2.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee10.sol
- infrastructure/smart-contracts/test/stakingv2/StakeKeysToPool.mjs
- packages/core/src/node-license/getKeysOfPool.ts
- packages/core/src/node-license/getUnStakedKeysOfUser.ts
This removes all key id dependencies from the staking implementation.
Update the StakingPool to version 2 that will only receive keyAmounts and will handle the internal state migration.
Update the PoolFactory2 to only pass keyAmounts to the StakingPool.
Update the Referee10 to not track the state for key ids assigned to a pool.
Update the TinyKeyAidrop to not stop processing and remove the id mapping.
This will compile, however, the testcases need to be updated for not having assignedKeyToPool on the Referee anymore.
> Moving to keyAmounts instead of key ids in staking Pool

- apps/web-connect/src/features/checkout/components/crossmint/CrossmintModal.tsx
Hide input to allow users to change the recipient address when minting with Crossmint.
> Removed User Change Recipient Address

- apps/web-connect/src/features/hooks/contract/useMintBatch.ts
Updated to display purchase successful if at least one mint succeded.
> fix: Display Purchase Success Page

- infrastructure/smart-contracts/.openzeppelin/unknown-421614.json
- infrastructure/smart-contracts/contracts/upgrades/StakingPool/StakingPool3.sol
- infrastructure/smart-contracts/contracts/upgrades/node-license/NodeLicense10.sol
- infrastructure/smart-contracts/contracts/upgrades/pool-factory/PoolFactory3.sol
- infrastructure/smart-contracts/contracts/upgrades/referee/Referee11.sol
- infrastructure/smart-contracts/package.json
- infrastructure/smart-contracts/scripts/transfer-staked-keys/upgrade-contracts.mjs
Implement transfer staked keys in NodeLicense10, Referee11, PoolFactory3 and StakingPool3
[sc-6861]
Add script to deploy upgrades for staked keys
Ran against testscases from https://github.com/xai-foundation/sentry/pull/576, the whole testsuite passes.
Deployed upgrades to sepolia, tested tranfer staked
https://sepolia.arbiscan.io//tx/0x57c52c6b8d39f0d9b89c0079ca05433d0a71119d22df0e899812f657166d1532
> Implement transfer staked keys
